#localized string data for verbose messaging, errors, and warnings.

ConvertFrom-StringData @'
    AddingDetail = Adding history detail
    AddingMinutes = Adding {0} minutes to start time
    AnotherSessionClock = A running countdown clock has been detected from another PowerShell session:
    BuildingSynchHash = Building a synchronized hashtable {0}
    Calculating = Calculating runtime for history id {0}
    CountdownAbort = Countdown aborted
    Creating = Creating
    CreatingFlag =  Creating the flag file {0}
    CreatingTimer = Creating timer {0}
    DeleteFlag = If this is incorrect, delete {0} and try again.
    DefaultLoading1 = Warming up the room
    DefaultLoading2 = Charging batteries
    DefaultLoading3 = Formatting C:
    DefaultLoading4 = Downloading Azure
    Detected = Detected host {0}
    DetectedParamSet = Detected parameter set {0}
    Ending = Ending module command {0}
    ExistingConsoleCountdown = A console-based countdown timer already exists
    ExistingConsoleTimer = A console-based timer is already running
    ExistingTimer = A timer with the name {0} already exists. Try again with a different name.
    ExportingTimer = Exporting {0} timer {1} to {2}
    ExportingTimerCount = Exporting {0} timer(s) to {1}
    FailedCreateTimer = Failed to create timer {0} {1}
    FailedFindHistory = Failed to find history with an ID of {0}
    FailedRemoveTimer = Failed to remove timer {0} {1}
    FindingAllVar = Finding all timer variables
    FindingVar = Finding timer variable {0}
    FoundMatchingTimer = Found {0} matching timer(s)
    GettingAll = Getting all timers
    GettingAllStatus = Getting all timers with a status of {0}
    GettingTimer = Getting timer {0}
    GettingTimerStatus = Getting timer status
    ImportingCount = Importing {0} timer(s)
    ImportingTimer = Importing timer {0}
    InitializingConsoleTimer = Initializing a new console timer
    InvalidDateFormat = The DateFormat value {0} is not a valid format string. Try something like F,G, or U which are case-sensitive.
    InvalidHost = This function only works in the console host. Try using Start-PSCountdown instead.
    Job = Job ID: {0}
    Launching = Launching the RunSpace
    Loading = Loading task messages from {0}
    NoConsoleCountdown = No console countdown was detected
    NoConsoleTimer = No console timer was detected
    NoCountDownTimer = Could not find $PSCountdownTimer in the global scope. Did you start a countdown timer?
    NoISE = This command will not work in the PowerShell ISE.
    NoMatchingTimer = Can't find a matching timer object. Would you like to create a new one?
    NoTimerFound = Can't find a timer called {0}. You need to start the timer first.
    PathNotFound = {0} not found. Using default values.
    Pausing = Pausing timer {0}
    ProcessingTimer = Processing {0}
    PromptAbort = Abort the command
    PromptCreate = Create a new timer
    RegisterConsoleCountdown = Registering an engine event for a console countdown
    RegisterConsoleTimer = Registering an engine event for a console timer
    RemoveFlag = Do you want to remove the flag file? Y/N
    RemovingTimer = Removing timer {0}
    RequiresWindows = This command requires a Windows platform.
    ResettingTimer = Resetting timer {0}
    RestartingTimer = Restarting timer {0}
    Running = Running under PowerShell version {0}
    RunningCountdownClock = You already have a countdown clock running. You can only have one clock running at a time.
    SettingStatus = Setting status to {0}
    SettingTimer = Setting timer {0}
    SettingTimerStart = Setting timer {0} start to {1}
    StartConsoleCountdown = Starting a console countdown for {0}
    StartedCountdown = Countdown timer started at {0}
    Starting = Starting module command {0}
    StartTitleCountdown = Starting a title countdown for {0}
    Stopping = Stopping PSCountdownClock
    StoppingConsoleCountdown = Attempting to stop a console countdown
    StoppingConsoleTimer = Attempting to stop a console timer
    Unregister = Unregistering event id: {0}
    UsingModule = Using PSTimers module version {0}
    UsingParameterSet = Using parameter set {0}
    UsingParams = Using PSBoundParameters:
    UsingSubscription = Using subscription id: {0}
    UsingTime = Using Time value
    Validating = Validating
    WarnNoNamedTimer = Can't find any matching timer objects with the name {0}.
    WarnNoTimers = No matching timers found.
    WarnNoTimersFound = No defined timers found. Use Start-MyTimer to create one.
    WarnNoTimerStatus = No timers found with a status of {0}
    WarnPause = You can only pause a running timer. The timer {0} has a status of {1}
    WarnResume = You can only resume a paused timer. The timer {0} has a status of {1}
    WarnTimerNotRunning = Timer {0} is not running.
'@
