#localized string data for verbose messaging, errors, and warnings.

ConvertFrom-StringData @'
    ExistingTimer = A timer with the name {0} already exists. Try again with a different name.
    AddingMinutes = Adding {0} minutes to start time
    AddingDetail = Adding history detail
    BuildingSynchHash = Building a synchronized hashtable {0}
    Calculating = Calculating runtime for history id {0}
    NoTimerFound  = Can't find a timer called {0}. You need to start the timer first.
    NoCountDownTimer = Could not find $PSCountdownTimer in the global scope. Did you start a countdown timer?
    CountdownAbort = Countdown aborted
    StartedCountdown = Countdown timer started at {0}
    CreatingFlag = Creating the flag file {0}
    CreatingTime = Creating timer {0}
    Creating = Creating
    DefiningRunspace = Defining the RunSpace command
    Detected = Detected host {0}
    DetectedParamSet = Detected parameter set {0}
    Ending = Ending module command {0}
    ExportingTimerCount = Exporting {0} timer(s) to {1}
    ExportingTimer  = Exporting {0} timer {1} to {2}
    FailedCreateTimer = Failed to create timer {0} {1}
    FailedFindHistory = Failed to find history with an ID of {0}
    FailedRemoveTimer = Failed to remove timer {0} {1}
    FindingAllVar = Finding all timer variables
    FindingVar = Finding timer variable {0}
    FoundMatchingTimer = Found {0} matching timer(s)
    GettingAll = Getting all timers
    GettingAllStatus = Getting all timers with a status of {0}
    GettingTimer = Getting timer {0}
    GettingTimerStatus = Getting timer status
    ImportingCount = Importing {0} timer(s)
    ImportingTimer = Importing timer {0}
    Job = Job ID: {0}
    Launching = Launching the RunSpace
    Loading = Loading task messages from {0}
    Pausing = Pausing timer {0}
    ProcessingTimer = Processing {0}
    RemovingTimer = Removing timer {0}
    ResettingTimer = Resetting timer {0}
    RestartingTimer = Restarting timer {0}
    Running = Running under PowerShell version {0}
    SettingStatus = Setting status to {0}
    SettingTimer = Setting timer {0}
    SettingTimerStart = Setting timer {0} start to {1}
    Starting = Starting module command {0}
    StartingTitleCountdown = Starting a title countdown for {0}
    Stopping = Stopping PSCountdownClock
    InvalidDateFormat = The DateFormat value {0} is not a valid format string. Try something like F,G, or U which are case-sensitive.
    RequiresWindows = This command requires a Windows platform.
    NoISE = This command will not work in the PowerShell ISE.
    InvalidHost = This function only works in the console host. Try using Start-PSCountdown instead.
    UsingParameterSet = Using parameter set {0}
    UsingParams = Using PSBoundParameters:
    UsingTime = Using Time value
    Validating = Validating
    WarnNoTimerStatus = No timers found with a status of {0}
    WarnNoTimers = No matching timers found.
    WarnNoTimersFound = No defined timers found. Use Start-MyTimer to create one.
    WarnNoNamedTimer = Can't find any matching timer objects with the name {0}.
    WarnRunningClock = You already have a clock running. You can only have one clock running at a time.
    WarnPause = You can only pause a running timer. The timer {0} has a status of {1}
    WarnResume = You can only resume a paused timer. The timer {0} has a status of {1}
'@
